SchemaVersion = 1

[[Packages]]
Name="Amc基础包"
Author="Amc白"
Desc = "Amc 基础包，用于提供一些空超武，单位，武器等用于其他ini的继承"
Version = 1
Url = "https://github.com/MeccBai/IniPackRepo/releases/download/2/AmcBase.zip"
Sha256 = "sha256:B3196AB2C67DA844787C76A27E766A6416079BF33A4F03AB5F41D7A0FBDF0517"
MinVersion = "1.0.0"

[[Packages]]
Name="Amc工具包"
Author="Amc白"
Desc = "Amc 工具包，提供：克隆工厂，矿石倍率，渗透单位建造等功能"
Version = 1
Url = "https://github.com/MeccBai/IniPackRepo/releases/download/2/AmcBase.zip"
Sha256 = "sha256:18E37C2086CF0E1944C3BAD59F76E5A706E2FC1D58FDB88B7F0D02E74EEB6670"
MinVersion = "1.0.0"